### ISSUE TITLE
Create PAT to trigger tebako-ci-container workflow from tebako master workflow

### ISSUE THREAD

**Issue by maxirmx** [tamatebako/tebako-ci-containers#20]
I would like to automatically publish new containers when a new version of tebako gem is released

In order to trigger tebako-ci-container workflow from tebako master workflow Personal Access Token is required
It shall be created in this ( tebako-ci-container) repository and added as a secret to tebako repository
(https://github.com/peter-evans/repository-dispatch#token)

Similar to this thread: https://github.com/rnpgp/ruby-rnp/issues/87

**Comment by ronaldtse** [comment]
The PAT secret is accessible under `secrets.TEBAKO_CI_PAT_TOKEN`.

**Comment by maxirmx** [comment]
Hi, Ronald
It fails with "Bad credentials"
Could you please check that it is available at tebako repository as well

Thank you

**Comment by ronaldtse** [comment]
@maxirmx I've regenerated the token, hope it works now? Let me know.

**Comment by maxirmx** [comment]
It works, thank you
